# Generated by Django 3.2 on 2021-05-02 12:34

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LasUpload',
            fields=[
                ('hashed_filename', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50)),
                ('las_file', models.FileField(upload_to='las/')),
            ],
        ),
    ]
