# Generated by Django 3.2 on 2021-11-16 06:14

from django.db import migrations, models
import las_viewer.utils
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('las_viewer', '0002_auto_20210703_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasupload',
            name='las_file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('D:/codes/python/WellCast-django/media/las'), validators=[las_viewer.utils.validate_is_las]),
        ),
    ]
